/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "Protocols/Protobuf/inc/titanium.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(NETWORK_CREDENTIALS, network_credentials_t, AUTO)


PB_BIND(ACCESS_POINT_INFORMATION, access_point_information_t, AUTO)


PB_BIND(STATION_INFORMATION, station_information_t, AUTO)


PB_BIND(NETWORK_INFORMATION, network_information_t, AUTO)


PB_BIND(ACCESS_POINT_STATUS, access_point_status_t, AUTO)


PB_BIND(STATION_STATUS, station_status_t, AUTO)


PB_BIND(BROKER_CONFIG, broker_config_t, 2)


PB_BIND(PACKET_REQUEST, packet_request_t, AUTO)


PB_BIND(CONTINUOS_PACKET_LIST, continuos_packet_list_t, AUTO)


PB_BIND(TIME_PROCESS, time_process_t, AUTO)


PB_BIND(MEMORY_AREAS_DEFINITIONS, memory_areas_definitions_t, 2)



